name: Rails CI

on:
  push:
  pull_request:

env:
  RUBY_VERSION: 3.4.5

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libpq-dev
          gem install bundler
          bundle config set --local path 'vendor/bundle'
          bundle install --jobs 4 --retry 3
      - name: Setup DB
        env:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: postgres
          PGPASSWORD: password
          PGPORT: 5432
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate
      - name: Run specs
        run: bundle exec rspec
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rspec-results
          path: coverage